package org.de.lmu.propra.test;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

import junit.framework.TestCase;

import org.de.lmu.propra.domain.PredictResult;
import org.de.lmu.propra.domain.Sequence;
import org.de.lmu.propra.domain.SequenceSequence;
import org.de.lmu.propra.gor.Gor;
import org.de.lmu.propra.gor.Gor4;
import org.de.lmu.propra.gor.Gor5;
import org.de.lmu.propra.gor.Gor5Impl;
import org.de.lmu.propra.util.FastaAASSReaderFunction;
import org.junit.Test;

public class Gor5Test {
//	> 1chmb
//	AS QMPKTLRIRNGDKVRSTFSAQEYANRQARLRAHLAAENIDAAIFTSYHNINYYSDFLYCSFGRPYALVVTEDDVISISANIDGGQPWRRTVGTDNIVYTDWQRDNYFAAIQQALPKARRIGIEHDHLNLQNRDKLAARYPDAELVDVAAACMRMR
//	SS CCCCEECCCCCCCCCCCCCHHHHHHHHHHHHHHHHHHCCCEEEECCHHHHHHHHCCCCCCCCCCCEEEECCCCEEEEEEHHHCCHHHHHCCCCEEEEECCCCCCHHHHHHHHHCCCCCEEEECCCCCEHHHHHHHHHHCCCCEEEECHHHHHHHH
//	1 DLERTKILQNGEKVKPTFSKEEMTRRNTRLREYMAKAGIDAVMFTSYHNINYYSDFLYTSFNRSYALVVTQDKHVTVSANIDAGMPWRRSF-DENIVYTDWKRDNFLYAVKKVLNESGRLGVENDHMTLDLRRQVQDALPNTELVDVSQAVMGHR
//	2 -----------------------MNRIQRVSSWLKEAGHTAAFIHTKENVFYLTGFYTEPHERLMGLFIFQEEPFFVCPGMEAGQARNAGWNHEIIGYADH--ENPWELIEKALKKIHMLAVEKDSISLSRAEQLKHATGGAQFVSAEETLNQFR
//	3 -----------------------MSKLAQIVQKLKKQGIEAAVLSDPVSINYLTGFYSDPHERLMFLFLFADQTLLFLPELDALRAKSILD-ISVTGYLDF--ENPLEKIKTLLPKYSKIALEFDNLNVTKFKGLETIFSG-QFTNLTPLINRMR

	@Test
	public void testGor5VsReference() {
		final String aatocheck1="QMPKTLRIRNGDKVRSTFSAQEYANRQARLRAHLAAENIDAAIF" +
				"TSYHNINYYSDFLYCSFGRPYALVVTEDDVISISANIDGGQPWRRTVGTDNIVYTDWQRD" +
				"NYFAAIQQALPKARRIGIEHDHLNLQNRDKLAARYPDAELVDVAAACMRMR";
		final String org = "CCCCEECCCCCCCCCCCCCHHHHHHHHHHHHHHHHHHCCCEEEECCHHH" +
				"HHHHHCCCCCCCCCCCEEEECCCCEEEEEEHHHCCHHHHHCCCCEEEEECCCCCCHHHHH" +
				"HHHHCCCCCEEEECCCCCEHHHHHHHHHHCCCCEEEECHHHHHHHH";
		final String alignment3="DLERTKILQNGEKVKPTFSKEEMTRRNTRLREYMAKAGIDAVMF" +
				"TSYHNINYYSDFLYTSFNRSYALVVTQDKHVTVSANIDAGMPWRRSF-DENIVYTDWKRD" +
				"NFLYAVKKVLNESGRLGVENDHMTLDLRRQVQDALPNTELVDVSQAVMGHR";
		final String alignment2="-----------------------MNRIQRVSSWLKEAGHTAAFI" +
				"HTKENVFYLTGFYTEPHERLMGLFIFQEEPFFVCPGMEAGQARNAGWNHEIIGYADH--E" +
				"NPWELIEKALKKIHMLAVEKDSISLSRAEQLKHATGGAQFVSAEETLNQFR";
		final String alignment1="-----------------------MSKLAQIVQKLKKQGIEAAVL" +
				"SDPVSINYLTGFYSDPHERLMFLFLFADQTLLFLPELDALRAKSILD-ISVTGYLDF--E" +
				"NPLEKIKTLLPKYSKIALEFDNLNVTKFKGLETIFSG-QFTNLTPLINRMR";

		FileReader reader = null;
		try {
			reader = new FileReader(new File("data/GOR/CB513DSSP.db"));
		} catch (FileNotFoundException e) {
		}
		ArrayList<SequenceSequence> listseqseq = FastaAASSReaderFunction
				.readDSSP(reader);
		
		Gor gor = new Gor4();
		gor.train(listseqseq);
		Gor5 gor5 = new Gor5Impl();
		List<Sequence> list=new ArrayList<Sequence>();
		list.add(new Sequence(0,aatocheck1,"AA",""));
		list.add(new Sequence(0,alignment1,"AA",""));
		list.add(new Sequence(0,alignment2,"AA",""));
		list.add(new Sequence(0,alignment3,"AA",""));
		PredictResult pr=gor5.predict(gor,list);
		System.out.println(org);
		System.out.println(pr.getSsseq().toString());
		System.out.println(pr.getPcseq().toString());
		System.out.println(pr.getPeseq().toString());
		System.out.println(pr.getPhseq().toString());
		
		TestCase.assertEquals(aatocheck1,pr.getAaseq().toString());
		
	}	
	
private static String aa1= "TALIGYARVSDGSQVHDLQRDALIKAGVEVDS-KQDDRPGLAACLK-LRAGDTLAVWKLDRLGRDLRHLVNLVDDLTKRNIGLKVLAASIDTSTANGRLVFGIFAALAEFERALI";
private static String aa2= "GQRIGYIRVSTFDQNPERQLEGVK---VDR-S-KDVKRPQLEALISFARTGDTVVVHSMDRLARNLDDLRRIVQTLTQRGVHIEFVKSFTGEDSPMANLMLSVMGAFAEFERALI";
private static String aa3= "SRIFAYCRISTLDQTTENQRREIESAGFKIKSAATSERPGFNRLLARLKCGDQLIVTKLDRLGCNAMDIRKTVEQLTETGIRVHCLAGGIDLTSPTGKMMMQVISAVAEFERDLL";
private static String aa4= "-MQIGYIRVSTNDQNTDLQRNALNCAGCEL-S-TKSARPGLKKLLRTLSEGDTLVVWKLDRLGRSMKHLITLIEELREKGVNFRSLTDSIDTSTPMGRFFFHVMGALAEMERELI";
private static String aa5= "MRLFGYARVSTSQQSLDVQIKALKAENVRATSGSHVNREGLRMLRLKVEEGDVVLVKKLDRLGRDTADMIQLIKEFDDMGVAIRFLDDGISTEGTMGKMVVTILSAVAQAERLRI";
private static String aa6= "-MNIGYARVSTGLQNLDLQKDSLGKYDCEK-S-SKKDR-GLKSAIEFSRPGDTIVVWRLDRLGRNMEDLISIVNSLNDKGVSFHSLQENITMDKSTGQLMFHLFAAFAEFERNLI";
private static String aa7= "-MLVGYMRVSSDRQSTDLQRDALP-AGVDPRS-AKDDR-AVWATSEFVCAGDVLVVWKLDRLGLSLSHLLAIVTSLKDKQVAFRSLTESLDTTTPSGEFLFQVFGALAQYERALI";
private static String aa8= "KNKYGYVRVSTQESNIESQKQQLIQNGIEEESNEIKNRSVFQKLINQLKDKDLLMVTKIDRCSRNTLEFLKLQDILFKKNITFVALDLPTSVDLATNKLMATTLSAMAEFENNRR";
private static String aa9= "-MIFGYARVSTDDQNLSLQIDALTHYGIDK-T-AKKDRPQLEEMINLLREGDSVVIYKLDRISRSTKHLIELSELFEELSVNFISIQDNVDTSTSMGRFFFRVMASLAELERDII";
private static String aa10= "-MIIGYARVSSLDQNLERQLENLKTFGAEK-SKSIENRPILQKALNFVRMGDRFIVESIDRLGRNYNEVIHTVNYLKDKEVQLMITSLPMMNEVIMKDLIIQILAMVSEQERNES";
private static String aa11= "MTKVGYARVSSKEQNLDRQLKALE--GVSK-SQSVE-RPQLQAMLNYIREGDIVVVTELDRLGRNNKELTELMNQIQIKGATLEVLNLPSMNGIEINNLVIELYKYQAESERKRI";
private static String aa12= "MATIGYIRVSTIDQNIDLQRNALTSANCDR-S-KIANRPGLKRALKYVNKGDTLVVWKLDRLGRSVKNLVALISELHERGAHFHSLTDSIDTSSAMGRFFFHVMSALAEMERELI";
private static String aa13= "MKALIYARVSKEQQELKRQEEELTANGMEVVS-YEMDRDGVFELLDENADIDVILVQDETRLGRGNAKIALLHCIYREGKVYTTAHRGELELSEA-DSMVLEIVSIVEEYQRKIH";
private static String aa14= "PKYYAYLRVSRDGQDPENQKYGLLEKGFAP-SRAKDWRKKLGAIIEKAERGDVLLTPEITRIAGSALAALEILKAASERGLIVHVTKQKIIMDGSQSDIMATVLGLAAQIERHFI";
private static String aa15= "-MIIGYARKSTHLQDVTHQVDELTKAGCEQ-SSKRAKNGELENCLKALREGDTLVVWALDRLGGSLSQVITLLDDLKKRGITFIAIKDRIDTSAPIGEIYTHLMAIFSNFERNRN";
private static String aa16= "-MLIGYARVSTADQDLRLQLDALQAAGCDK-S-KKLDRAGLVDALAFAREGDTLVVWKLDRLGRSMKGLVDLAADLDARKVDLRSLTDGIRHQRHRWPLLLSRLAAMAEMERELI";
private static String aa17= "GKVFGYARVSTQDQILDLQIDVLEKAGAAV-T-TRKERPELEQLLKAISKGDSVVVYKLDRISRSTKHLIELVETFEEKEVNFISIQDNIDTSTAMGRFFFRTMASIAELERDII";
private static String aa18=  "----------------------MRAAGVERDS-GRDDRPGLTACLKSLRDGDVLVVWKLDRLGRSLAHLVNTVKELSDRKIGLRVLTAQIDTTTASGRMVFGIFATLAEFERDLI";
private static String aa19 = "QRLIGYARVSTEDQLNDAQVDELRAAGCHR-S-ASRARPVLAKLLKDLAMGDVLVVVRLDRLARSVSHLLDVIEDLEKRGVHFRSLRDPIDTSTPHGMFSLQVLGAVAQLERALI";
private static String aa20 = "-MLIGYARVSTQDQNLELQRESLSKAGCQK-S-TRADRPGLAKALEMLREDDTLVVWKLDRLGRSVKQLVDLVGDLHKQGIQFRSLTDSIDTGTPSGRFFFHVMASLAEMERELT";
private static String aa21 = "MALIGYARVSTAEQDTALQTDAYGKAGCER-P-LSQTRHALAAALAYLRDGDVLAVWRLDRFGRSLPHLIETISALEARGVRFRSLTDSIDTTTPGGRLIFHVFGALGQFERDLI";
private static String aa22 = "-MKIGYARVSTREQNPALQVDSLKAAGCER-S-AKTARPALDELLGQLRGGDVLVIWKLDRMGRSLKHLVELVGSLMERKVGLLSLNDPIDTTSAQGRFVFNLFATLAEFERELI";
private static String aa23 = "GKRLGYARVSTDDQRLDLQRDALTRAGCAD-S-KSADR-ALDYCLRALSAGDTLVVWRLDRLGRSLPDLVRIVGELEQRGVGFESVTERIETGS-TGKLTFHLFSALAEFERNLI";
private static String aa24 = "NQRIGYARVSTQDQHFDLQRDALLQAGCGV-S-KNAMR-ELEQCLKALRSGDTLVVWRLDRLGHSLPDLVQVVSDLERSGIGFESLTEKIETVS-AGKLVFHVFAALAEFERSLI";
private static String aa25 = "MAKIGYARVSSKEQHLDRQLAALK--DVDK-SANTN-RPELQKMLAYIREGDIVLVTELDRLGRNNQDLTKIMNTIPNKGATLDVLNLPSMTGIAMTNLIIELYKYQAESERKRI";
private static String aa26 = "HRAAIYCRVSTADQSCERQEFDLRAAGYDVVS-TKLDRAKKVLALAQSRQIDAILVTELSRWGRSTLDLLNTLRELENWKVSVIAMNMAFDLSSPYGRMLATFLSGIAEFERDLI";
private static String aa27 = "-MLVGYARVSTEEQSLNRQIDMLVDYGVDKRS-MKPNREQLDKMIDELQEGDTVIITDLTRISRSTKDLLNIIDRIKAKGASIKSIKTWLDTSSDYNSFLLTVMSGLSQLERDLI";
private static String aa28 = "MRKIGYIRVSSTNQNPSRQFQQLNEIGMD--S-ATKDREQLQKVLDDLQEDDIIYVTDLTRITRSTQDLFELIDNIRDKKASLKSLKTWLDLSEDYSQFLITVMAGVNQLERDLI";
private static String aa29 = "MENWGYARVSGEEQQLRKQIERLRNAGCSK-SRTTEVREQLINDLKTTGKVKSLQFTRIDRIGSSSRLFYSLLEVLRSKGIKLIALDQGVDPDS-GGELTIDMLLAAAKFEVRMV";
private static String aa30 = "MARIGYARTFTTDQNLAAQIAALRNAGCEV-SASLEGRPQLMTILDFIHAGETFVITRIDRLARSLRDLQVIVDRLKAKGAHLVATEQPADTSTAAGKAFFDMLGVFAGFETNLR";
private static String aa31 = "MALYGYARVSTSDQDLTLQTQILRAAGCEI-SSGRTGRSELQLLLEFLRPGDTLMVTRVDRLARSIKDLQDIVYALNQQGVTLRATEHQWNT-----------------------";
private static String aa32 = "MRIFGYARLSTSQQSLDIQIRALKDAGVKLTRSSTD-REGLDLLRMKVEEGDVILVKKLDRLGRDTADMIQLIKEFDAQGVAVRFIDDGISTDGDTGQMVVTILSAVASAERRRI";
private static String aa33 = "-MKIGYARVSTFEQKLESQIEVLKEAGAEE-T-TTVERPQFNLVFKKLKDGDTLIVTKLDRLARNTREVLEIVQSLFNRGIKVHILNGLIDNTP-TGQLIFTIFSAFAQFERDLI";
private static String aa34 = "-MKYGYARVSTIDQKLESQIEQLKNAGAEE-T-TTNSRPAFINLLNTLESGDTLIITKLESFARNPREALATIQELFDKDIKINILNGVIDNTA-TGKLIFTIFSAFAQFERDMI";
private static String aa35 = "KKVAIYTRVSTTNQAIDEQIDRLTKMGWQVSF-AKLERPAMQRLINDNKAFDTVLVYKLDRLSRSVRDTLYLVKDVFTKKIDFISLNESIDTSSAMGSLFLTILSAINEFERENI";
private static String aa36 = "-MIAIYVRVSTEEQAIDSQIEACIKAGTKD-F-ELLERPALNRLREDKGLISQVICYDPDRLSRKLMNQLIIDDELRKRNIPLIFVNGEYANSPE-GQLFFAMRGAISEFEKAKI";
	@Test
	public void testGor5v2VsReference() {
		final String aatocheck1="MRLFGYARVSTSQQSLDIQVRALKDAGVKANRIFTDKRKGLDLL" +
				"RMKVEEGDVILVKKLDRLGRDTADMIQLIKEFDAQGVSIRFIDDGISTDGEMGKMVVTIL" +
				"SAVAQAERQRI";
		final String org = "CEEEEEEECCCCHHHHHHHHHHHHHCCCCHHHEEEECCHHHHHHCCCCC" +
				"CCEEEEECCHHHCCCCHHHHHHHHHHHHHCCCEEEECCCCEECCHHHHHHHHHHHHHHHH" +
				"HHHHHC";
		final String toCheck = "--------CEEEHHHHHHHHHHHHHEEEEHHHEHHHHHHHHHHHHHHHEEEEHHCHHHHHHEEEEHHHHHHHHHHHHHEEHHCCCCEEEEEEEEEEEHHHHHHHHHH--------";

		
		FileReader reader = null;
		try {
			reader = new FileReader(new File("data/GOR/CB513DSSP.db"));
		} catch (FileNotFoundException e) {
		}
		ArrayList<SequenceSequence> listseqseq = FastaAASSReaderFunction
				.readDSSP(reader);
		
		Gor gor = new Gor4();
		gor.train(listseqseq);
		Gor5 gor5 = new Gor5Impl();
		List<Sequence> list=new ArrayList<Sequence>();
		list.add(new Sequence(0,aatocheck1,"AA",""));
		list.add(new Sequence(0,aa1,"AA",""));
		list.add(new Sequence(0,aa2,"AA",""));
		list.add(new Sequence(0,aa3,"AA",""));
		list.add(new Sequence(0,aa4,"AA",""));
		list.add(new Sequence(0,aa5,"AA",""));
		list.add(new Sequence(0,aa6,"AA",""));
		list.add(new Sequence(0,aa7,"AA",""));
		list.add(new Sequence(0,aa8,"AA",""));
		list.add(new Sequence(0,aa9,"AA",""));
		list.add(new Sequence(0,aa10,"AA",""));
		list.add(new Sequence(0,aa11,"AA",""));
		list.add(new Sequence(0,aa12,"AA",""));
		list.add(new Sequence(0,aa13,"AA",""));
		list.add(new Sequence(0,aa14,"AA",""));
		list.add(new Sequence(0,aa15,"AA",""));
		list.add(new Sequence(0,aa16,"AA",""));
		list.add(new Sequence(0,aa17,"AA",""));
		list.add(new Sequence(0,aa18,"AA",""));
		list.add(new Sequence(0,aa19,"AA",""));
		list.add(new Sequence(0,aa20,"AA",""));
		list.add(new Sequence(0,aa21,"AA",""));
		list.add(new Sequence(0,aa22,"AA",""));
		list.add(new Sequence(0,aa23,"AA",""));
		list.add(new Sequence(0,aa24,"AA",""));
		list.add(new Sequence(0,aa25,"AA",""));
		list.add(new Sequence(0,aa26,"AA",""));
		list.add(new Sequence(0,aa27,"AA",""));
		list.add(new Sequence(0,aa28,"AA",""));
		list.add(new Sequence(0,aa29,"AA",""));
		list.add(new Sequence(0,aa30,"AA",""));
		list.add(new Sequence(0,aa31,"AA",""));
		list.add(new Sequence(0,aa32,"AA",""));
		list.add(new Sequence(0,aa33,"AA",""));
		list.add(new Sequence(0,aa34,"AA",""));
		list.add(new Sequence(0,aa35,"AA",""));
		list.add(new Sequence(0,aa36,"AA",""));

		PredictResult pr=gor5.predict(gor,list);
		System.out.println(org);
		System.out.println(toCheck);
		System.out.println(pr.getSsseq().toString());
		System.out.println(pr.getPcseq().toString());
		System.out.println(pr.getPeseq().toString());
		System.out.println(pr.getPhseq().toString());

		TestCase.assertEquals(aatocheck1,pr.getAaseq().toString());
		
	}
}

